-- show_rules and stock belong to Inventory (ADR-006). show_id and
-- category_id are generated by Catalog, in Catalog's own database, so there
-- is no server-side default here and no foreign key back to Catalog
-- (ADR-001: each service owns its own data and shares only ids).
CREATE TABLE IF NOT EXISTS show_rules (
    show_id UUID PRIMARY KEY,
    organizer_id UUID NOT NULL,
    on_sale_at TIMESTAMPTZ NULL,
    max_per_customer INT NOT NULL,
    hold_minutes INT NOT NULL,
    high_demand BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS stock (
    show_id UUID NOT NULL,
    category_id UUID NOT NULL,
    capacity INT NOT NULL,
    available INT NOT NULL CHECK (available >= 0),
    unit_price NUMERIC(12, 2) NOT NULL,
    currency CHAR(3) NOT NULL,
    allocation_mode TEXT NOT NULL DEFAULT 'GA',
    PRIMARY KEY (show_id, category_id)
);
